// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzwhciinudtuqsdssqmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6d2hjaWludWR0dXFzZHNzcW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMTYxMjAsImV4cCI6MjA1NDY5MjEyMH0.WoSbR1k0loyT2mKJwhQY1GwjuBFjl-O199Mf8ZIBFfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);